[project]
name = "minimal-pixel-meanflow"
version = "0.1.0"
description = "Train few step generative pixel-space models"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bpython>=0.26",
    "datasets>=4.5.0",
    "einops>=0.8.2",
    "jsonargparse>=4.45.0",
    "lpips>=0.1.4",
    "numpy>=2.4.1",
    "torch>=2.10.0",
    "torchcodec>=0.10.0",
    "torchvision>=0.25.0",
    "tqdm>=4.67.1",
    "transformers>=5.0.0",
    "wandb>=0.24.1",
]
